#!/usr/bin/env python3
"""Generates Localizable.xcstrings (az, ru) for AdminFeatures.

Terms follow the main app's dictionary (Emin-dev/iOS localization/strings-en-az-ru.csv):
Host = Sahibkar / Владелец, Renter = İcarəçi, Golf cart = Qolf karı, Wallet = Pul kisəsi.

Run: python3 scripts/strings.py   (then commit the regenerated catalogue)
"""
import json
import pathlib

T = {
    # Formats
    "%@ take rate": ("%@ komissiya", "комиссия %@"),
    "%@ · CSV": ("%@ · CSV", "%@ · CSV"),
    "%lld items": ("%lld qeyd", "Записей: %lld"),
    "%lld waiting": ("%lld gözləyir", "Ждут: %lld"),
    "Updated %@": ("Yeniləndi: %@", "Обновлено: %@"),
    "Rentbutik Admin · version %@": ("Rentbutik Admin · versiya %@", "Rentbutik Admin · версия %@"),
    # Tabs and shell
    "Home": ("Ana səhifə", "Главная"),
    "Inbox": ("Gələnlər", "Входящие"),
    "Platform": ("Platforma", "Платформа"),
    "Search": ("Axtarış", "Поиск"),
    "Module": ("Modul", "Модуль"),
    "View": ("Görünüş rejimi", "Режим"),
    "CEO": ("CEO", "CEO"),
    "Investor": ("İnvestor", "Инвестор"),
    "Switch between CEO and Investor view": ("CEO və İnvestor görünüşü arasında keçid", "Переключить вид CEO / Инвестор"),
    "Account": ("Hesab", "Аккаунт"),
    "Language": ("Dil", "Язык"),
    "Appearance": ("Görünüş", "Оформление"),
    "System": ("Sistem", "Системное"),
    "Light": ("Açıq", "Светлое"),
    "Dark": ("Tünd", "Тёмное"),
    "Sign out": ("Çıxış", "Выйти"),
    "Sign in": ("Daxil ol", "Войти"),
    "Email": ("E-poçt", "Эл. почта"),
    "Password": ("Şifrə", "Пароль"),
    "For Rentbutik admins only. Staff and drivers use the Rentbutik app.": (
        "Yalnız Rentbutik adminləri üçün. Əməkdaşlar və sürücülər Rentbutik tətbiqindən istifadə edir.",
        "Только для администраторов Rentbutik. Сотрудники и водители работают в приложении Rentbutik."),
    "The new backend is not connected yet. Any email and a password of 4+ characters open the app with sample data.": (
        "Yeni backend hələ qoşulmayıb. İstənilən e-poçt və ən azı 4 simvollu şifrə ilə tətbiq nümunə məlumatla açılır.",
        "Новый бэкенд ещё не подключён. Любая почта и пароль от 4 символов открывают приложение с демо-данными."),
    "Email or password is wrong.": ("E-poçt və ya şifrə yanlışdır.", "Неверная почта или пароль."),
    "This item no longer exists.": ("Bu qeyd artıq mövcud deyil.", "Эта запись больше не существует."),
    "Sample data": ("Nümunə məlumat", "Демо-данные"),
    "Sample data, not real numbers": ("Nümunə məlumat, real rəqəmlər deyil", "Демо-данные, не реальные цифры"),
    "Loading": ("Yüklənir", "Загрузка"),
    "Could not load": ("Yükləmək alınmadı", "Не удалось загрузить"),
    "Try again": ("Yenidən cəhd et", "Повторить"),
    "Across all modules": ("Bütün modullar üzrə", "По всем модулям"),
    "This app": ("Bu tətbiq", "Это приложение"),
    # Actions lock
    "Actions on. Tap to lock.": ("Əməliyyatlar açıqdır. Kilidləmək üçün toxunun.", "Действия включены. Нажмите, чтобы заблокировать."),
    "Actions off. Tap to unlock.": ("Əməliyyatlar bağlıdır. Açmaq üçün toxunun.", "Действия выключены. Нажмите, чтобы разблокировать."),
    "Actions are locked. Unlock them first.": ("Əməliyyatlar kilidlidir. Əvvəlcə kilidi açın.", "Действия заблокированы. Сначала разблокируйте их."),
    "Actions are off. Unlock them first.": ("Əməliyyatlar bağlıdır. Əvvəlcə kilidi açın.", "Действия выключены. Сначала разблокируйте их."),
    "Actions are off. Unlock with the lock button to use them.": (
        "Əməliyyatlar bağlıdır. İstifadə üçün kilid düyməsi ilə açın.", "Действия выключены. Разблокируйте их кнопкой с замком."),
    "Unlock admin actions for 15 minutes": ("Admin əməliyyatlarını 15 dəqiqəlik açın", "Разблокировать действия на 15 минут"),
    "Action failed": ("Əməliyyat alınmadı", "Действие не выполнено"),
    "This changes live data.": ("Bu, canlı məlumatı dəyişir.", "Это изменит рабочие данные."),
    "This changes live data. The user may be notified.": (
        "Bu, canlı məlumatı dəyişir. İstifadəçiyə bildiriş gedə bilər.", "Это изменит рабочие данные. Пользователь может получить уведомление."),
    "Cancel": ("Ləğv et", "Отмена"),
    "OK": ("OK", "OK"),
    # Dashboard
    "Live": ("Canlı", "Сейчас"),
    "trips on the road": ("səfər yoldadır", "поездок в пути"),
    "carts out now": ("qolf karı hazırda icarədədir", "гольф-каров сейчас в аренде"),
    "rides on the road": ("transfer yoldadır", "трансферов в пути"),
    "Revenue today": ("Bugünkü gəlir", "Выручка сегодня"),
    "Needs you": ("Qərarınızı gözləyir", "Ждут решения"),
    "Pages": ("Bölmələr", "Разделы"),
    "Recent trips": ("Son səfərlər", "Последние поездки"),
    "All trips": ("Bütün səfərlər", "Все поездки"),
    "Listed cars": ("Elandakı avtomobillər", "Машины в каталоге"),
    "Reviews to check": ("Yoxlanacaq rəylər", "Отзывы на проверку"),
    "active holds": ("aktiv bron", "активных броней"),
    "users owe money": ("istifadəçinin borcu var", "пользователей с долгом"),
    "open": ("açıq", "открыто"),
    "appeals to review": ("baxılacaq etiraz", "апелляций на рассмотрении"),
    "Carts": ("Qolf karları", "Гольф-кары"),
    "Bookings to approve": ("Təsdiq gözləyən bronlar", "Брони на подтверждение"),
    "waiting for the Sea Breeze team": ("Sea Breeze komandasını gözləyir", "ждут команду Sea Breeze"),
    "Live routes": ("Aktiv marşrutlar", "Активные маршруты"),
    "waiting for approval": ("təsdiq gözləyir", "ждут подтверждения"),
    # Investor
    "Gross bookings this month": ("Bu ayın ümumi sifariş həcmi", "Оборот бронирований за месяц"),
    "Active riders · 30 days": ("Aktiv istifadəçilər · 30 gün", "Активные клиенты · 30 дней"),
    "Retention · 30 days": ("Geri qayıdış · 30 gün", "Удержание · 30 дней"),
    "came back for a second trip": ("ikinci səfərə qayıtdı", "вернулись на вторую поездку"),
    "Fleet utilisation": ("Parkın istifadəsi", "Загрузка автопарка"),
    "of fleet hours earning": ("park saatlarının gəlir gətirən hissəsi", "часов автопарка приносят доход"),
    "Revenue per trip": ("Səfər başına gəlir", "Выручка за поездку"),
    "own fleet, full fare": ("öz parkımız, tam tarif", "свой автопарк, полный тариф"),
    "Activation funnel": ("Aktivləşmə qıfı", "Воронка активации"),
    "Revenue mix": ("Gəlir strukturu", "Структура выручки"),
    "When people ride": ("İnsanlar nə vaxt sürür", "Когда ездят"),
    "Month": ("Ay", "Месяц"),
    "Bookings": ("Bronlar", "Бронирования"),
    "Share": ("Pay", "Доля"),
    "Type": ("Növ", "Тип"),
    "Hour": ("Saat", "Час"),
    "Registered": ("Qeydiyyatdan keçib", "Зарегистрированы"),
    "Documents verified": ("Sənədləri təsdiqlənib", "Документы подтверждены"),
    "First trip": ("İlk səfər", "Первая поездка"),
    "Second trip": ("İkinci səfər", "Вторая поездка"),
    "Active in 30 days": ("30 gündə aktiv", "Активны за 30 дней"),
    "Per minute": ("Dəqiqəlik", "Поминутно"),
    "Hourly": ("Saatlıq", "Почасово"),
    "Daily": ("Günlük", "Посуточно"),
    "With driver": ("Sürücü ilə", "С водителем"),
    "EV plans": ("EV planları", "EV-планы"),
    "Personal hosts": ("Fərdi sahibkarlar", "Частные владельцы"),
    "Commercial hosts": ("Kommersiya sahibkarları", "Коммерческие владельцы"),
    "Apr": ("Apr", "Апр"), "May": ("May", "Май"), "Jun": ("İyn", "Июн"),
    "Jul": ("İyl", "Июл"), "Aug": ("Avq", "Авг"), "Sep": ("Sen", "Сен"),
    # Statistics
    "Morning · 6–11": ("Səhər · 6–11", "Утро · 6–11"),
    "Afternoon · 12–16": ("Gündüz · 12–16", "День · 12–16"),
    "Evening · 17–22": ("Axşam · 17–22", "Вечер · 17–22"),
    "Off-hours · 23–05": ("Gecə · 23–05", "Ночь · 23–05"),
    "trips per day": ("səfər gündə", "поездок в день"),
    "Trips by hour": ("Saatlar üzrə səfərlər", "Поездки по часам"),
    "Unique riders": ("Unikal istifadəçilər", "Уникальные клиенты"),
    # Map
    "Busy": ("Məşğul", "Заняты"),
    "Needs attention": ("Diqqət tələb edir", "Требуют внимания"),
    "Other": ("Digər", "Другое"),
    # Lists
    "Show more": ("Daha çox göstər", "Показать ещё"),
    "Export CSV": ("CSV ixrac et", "Экспорт CSV"),
    "Search name, phone or ID": ("Ad, telefon və ya ID axtarın", "Имя, телефон или ID"),
    "All": ("Hamısı", "Все"),
    "Nothing waiting": ("Gözləyən heç nə yoxdur", "Ничего не ждёт"),
    "Every request has been handled.": ("Bütün sorğulara baxılıb.", "Все запросы обработаны."),
    "Search everything": ("Hər yerdə axtarın", "Поиск по всему"),
    "Name, phone, plate, promo code or ID.": ("Ad, telefon, nömrə nişanı, promo kod və ya ID.", "Имя, телефон, госномер, промокод или ID."),
    # Modules
    "P2P": ("P2P", "P2P"),
    "EV": ("EV", "EV"),
    "Golf": ("Qolf", "Гольф"),
    "Transfer": ("Transfer", "Трансфер"),
    "Car rental (P2P)": ("Avtomobil icarəsi (P2P)", "Аренда авто (P2P)"),
    "Electric carsharing": ("Elektrik karşerinq", "Электрокаршеринг"),
    "Golf · Sea Breeze": ("Qolf · Sea Breeze", "Гольф · Sea Breeze"),
    "Transfer marketplace": ("Transfer bazarı", "Маркетплейс трансферов"),
    # Pages
    "Overview": ("İcmal", "Обзор"),
    "Users": ("İstifadəçilər", "Пользователи"),
    "Vehicles": ("Avtomobillər", "Автомобили"),
    "Trips": ("Səfərlər", "Поездки"),
    "Map": ("Xəritə", "Карта"),
    "Reserves": ("Bronlar", "Брони"),
    "Outstanding debt": ("Ödənilməmiş borclar", "Задолженности"),
    "Damage reports": ("Zədə hesabatları", "Отчёты о повреждениях"),
    "Statistics": ("Statistika", "Статистика"),
    "Host reviews": ("Sahibkar rəyləri", "Отзывы о владельцах"),
    "Renter reviews": ("İcarəçi rəyləri", "Отзывы об арендаторах"),
    "Ops queues": ("Əməliyyat növbələri", "Операционные очереди"),
    "Notifications": ("Bildirişlər", "Уведомления"),
    "Promo codes": ("Promo kodlar", "Промокоды"),
    "Settings": ("Ayarlar", "Настройки"),
    "Parking warnings": ("Parkinq xəbərdarlıqları", "Предупреждения о парковке"),
    "Driver requests": ("Sürücü sorğuları", "Заявки на водителя"),
    "Fleet": ("Park", "Автопарк"),
    "Transactions": ("Əməliyyatlar tarixçəsi", "Транзакции"),
    "Tariffs": ("Tariflər", "Тарифы"),
    "Zones": ("Zonalar", "Зоны"),
    "Staff & drivers": ("Əməkdaşlar və sürücülər", "Сотрудники и водители"),
    "Routes": ("Marşrutlar", "Маршруты"),
    "Drivers": ("Sürücülər", "Водители"),
    "Car checks": ("Avtomobil yoxlamaları", "Проверки машин"),
    "Payouts & fees": ("Ödənişlər və komissiyalar", "Выплаты и комиссии"),
    "Document checks": ("Sənəd yoxlamaları", "Проверка документов"),
    "Listing reviews": ("Elan yoxlamaları", "Проверка объявлений"),
    "Support inbox": ("Dəstək sorğuları", "Обращения в поддержку"),
    "Company accounts": ("Şirkət hesabları", "Корпоративные аккаунты"),
    "News & push": ("Xəbərlər və bildirişlər", "Новости и пуши"),
    "Admins & roles": ("Adminlər və rollar", "Админы и роли"),
    "Security groups": ("Təhlükəsizlik qrupları", "Группы безопасности"),
    "Localization": ("Lokalizasiya", "Локализация"),
    "Car data": ("Avtomobil məlumatları", "Справочник авто"),
    # Queue kinds
    "Document check": ("Sənəd yoxlaması", "Проверка документов"),
    "Listing review": ("Elan yoxlaması", "Проверка объявления"),
    "Golf booking": ("Qolf bronu", "Бронь гольф-кара"),
    "Golf driver request": ("Qolf sürücü sorğusu", "Заявка на водителя (гольф)"),
    "EV driver request": ("EV sürücü sorğusu", "Заявка на водителя (EV)"),
    "Parking appeal": ("Parkinq etirazı", "Апелляция по парковке"),
    "Support chat": ("Dəstək çatı", "Чат поддержки"),
    "Transfer car check": ("Transfer avtomobil yoxlaması", "Проверка машины для трансфера"),
    "Cancellation request": ("Ləğv sorğusu", "Запрос на отмену"),
    "Damage report": ("Zədə hesabatı", "Отчёт о повреждении"),
    # Actions
    "Block user": ("İstifadəçini blokla", "Заблокировать"),
    "Unblock user": ("Bloku götür", "Разблокировать"),
    "Verify documents": ("Sənədləri təsdiqlə", "Подтвердить документы"),
    "Reject documents": ("Sənədləri rədd et", "Отклонить документы"),
    "Approve listing": ("Elanı təsdiqlə", "Одобрить объявление"),
    "Request changes": ("Düzəliş istə", "Запросить правки"),
    "Block vehicle": ("Avtomobili blokla", "Заблокировать машину"),
    "Unblock vehicle": ("Avtomobilin blokunu götür", "Разблокировать машину"),
    "Approve and assign": ("Təsdiqlə və təyin et", "Подтвердить и назначить"),
    "Decline booking": ("Bronu rədd et", "Отклонить бронь"),
    "Cancel trip": ("Səfəri ləğv et", "Отменить поездку"),
    "End trip": ("Səfəri bitir", "Завершить поездку"),
    "Assign driver": ("Sürücü təyin et", "Назначить водителя"),
    "Decline request": ("Sorğunu rədd et", "Отклонить заявку"),
    "Approve car check": ("Yoxlamanı təsdiqlə", "Одобрить проверку"),
    "Reject car check": ("Yoxlamanı rədd et", "Отклонить проверку"),
    "Mark resolved": ("Həll edildi kimi qeyd et", "Отметить решённым"),
    "Hide review": ("Rəyi gizlət", "Скрыть отзыв"),
    "Deactivate promo": ("Promonu dayandır", "Отключить промокод"),
    # Statuses
    "Active": ("Aktiv", "Активен"),
    "Blocked": ("Bloklanıb", "Заблокирован"),
    "Waiting for check": ("Yoxlama gözləyir", "Ждёт проверки"),
    "Unverified": ("Təsdiqlənməyib", "Не подтверждён"),
    "Verified": ("Təsdiqlənib", "Подтверждено"),
    "Rejected": ("Rədd edildi", "Отклонено"),
    "In review": ("Yoxlamada", "На проверке"),
    "Live": ("Canlı", "Сейчас"),
    "Needs changes": ("Düzəliş lazımdır", "Нужны правки"),
    "Available": ("Boşdur", "Свободна"),
    "On trip": ("Səfərdədir", "В поездке"),
    "Charging": ("Enerji yığır", "Заряжается"),
    "Low battery": ("Batareya azdır", "Низкий заряд"),
    "Paused": ("Dayandırılıb", "Приостановлено"),
    "On rental": ("İcarədədir", "В аренде"),
    "Pending approval": ("Təsdiq gözləyir", "Ждёт подтверждения"),
    "Approved": ("Təsdiqlənib", "Подтверждено"),
    "Active hold": ("Aktiv bron", "Активная бронь"),
    "Expired": ("Vaxtı bitib", "Истёк"),
    "Waiting": ("Gözləyir", "Ожидает"),
    "Driver assigned": ("Sürücü təyin edilib", "Водитель назначен"),
    "Finished": ("Başa çatıb", "Завершена"),
    "Ongoing": ("Davam edir", "Идёт"),
    "Cancelled": ("Ləğv edildi", "Отменено"),
    "Waiting for host": ("Sahibkar gözlənilir", "Ждём владельца"),
    "Upcoming": ("Qarşıdakı", "Предстоящие"),
    "Declined": ("Rədd edildi", "Отклонено"),
    "Overdue": ("Gecikib", "Просрочено"),
    "Owes": ("Borcu var", "Есть долг"),
    "Appealed": ("Etiraz edilib", "Обжаловано"),
    "Fee charged": ("Cərimə tutulub", "Штраф списан"),
    "Warning sent": ("Xəbərdarlıq göndərilib", "Предупреждение отправлено"),
    "Waiting for approval": ("Təsdiq gözləyir", "Ждёт одобрения"),
    "Open": ("Açıq", "Открыто"),
    "Resolved": ("Həll edilib", "Решено"),
    "Flagged": ("İşarələnib", "Помечен"),
    "Published": ("Dərc edilib", "Опубликован"),
    "Hidden": ("Gizlədilib", "Скрыт"),
    "Paid": ("Ödənilib", "Оплачено"),
    "Refunded": ("Geri qaytarılıb", "Возврат"),
    "Failed": ("Alınmadı", "Ошибка"),
    "Sent": ("Göndərilib", "Отправлено"),
    "Scheduled": ("Planlaşdırılıb", "Запланировано"),
    "Draft": ("Qaralama", "Черновик"),
    "Inactive": ("Deaktivdir", "Неактивен"),
    "On sale": ("Satışdadır", "В продаже"),
    "Alert": ("Xəbərdarlıq", "Тревога"),
    "Online": ("Onlayn", "Онлайн"),
    "Offline": ("Oflayn", "Офлайн"),
    "Complete": ("Tamamdır", "Готово"),
    "12 missing": ("12 çatışmır", "Не хватает 12"),
    # Sections and fields
    "Status": ("Status", "Статус"),
    "Profile": ("Profil", "Профиль"),
    "Phone": ("Telefon", "Телефон"),
    "Account type": ("Hesab növü", "Тип аккаунта"),
    "Company": ("Şirkət", "Компания"),
    "Personal": ("Fərdi", "Личный"),
    "Documents": ("Sənədlər", "Документы"),
    "Verification": ("Təsdiqləmə", "Проверка"),
    "MyGov": ("MyGov", "MyGov"),
    "5 photos": ("5 foto", "5 фото"),
    "ID card": ("Şəxsiyyət vəsiqəsi", "Удостоверение личности"),
    "Driving licence": ("Sürücülük vəsiqəsi", "Водительское удостоверение"),
    "Selfie with ID": ("Vəsiqə ilə selfi", "Селфи с документом"),
    "Uploaded": ("Yüklənib", "Загружено"),
    "Missing": ("Yoxdur", "Нет"),
    "Activity": ("Fəaliyyət", "Активность"),
    "Modules": ("Modullar", "Модули"),
    "Wallet balance": ("Pul kisəsi balansı", "Баланс кошелька"),
    "Debt": ("Borc", "Долг"),
    "Vehicle": ("Avtomobil", "Автомобиль"),
    "Plate": ("Nömrə nişanı", "Госномер"),
    "Price": ("Qiymət", "Цена"),
    "Battery": ("Batareya", "Заряд"),
    "Host": ("Sahibkar", "Владелец"),
    "Performance": ("Göstəricilər", "Показатели"),
    "Earnings": ("Qazanc", "Доход"),
    "Rating": ("Reytinq", "Рейтинг"),
    "Papers": ("Sənədlər", "Документы"),
    "Insurance": ("Sığorta", "Страховка"),
    "Portal registration": ("Portalda qeydiyyat", "Регистрация на портале"),
    "Registered": ("Qeydiyyatdan keçib", "Зарегистрирован"),
    "Trip": ("Səfər", "Поездка"),
    "Renter": ("İcarəçi", "Арендатор"),
    "From": ("Haradan", "Откуда"),
    "To": ("Haraya", "Куда"),
    "Duration": ("Müddət", "Длительность"),
    "Passengers": ("Sərnişinlər", "Пассажиры"),
    "Arrival": ("Gəliş", "Прибытие"),
    "Money": ("Ödəniş", "Оплата"),
    "Paid with": ("Ödəniş üsulu", "Способ оплаты"),
    "Wallet": ("Pul kisəsi", "Кошелёк"),
    "Apple Pay": ("Apple Pay", "Apple Pay"),
    "Company invoice": ("Şirkət hesab-fakturası", "Счёт компании"),
    "Promo": ("Promo", "Промо"),
    "None": ("Yoxdur", "Нет"),
    "Fee": ("Komissiya", "Комиссия"),
    "Photos": ("Fotolar", "Фото"),
    "Before": ("Səfərdən əvvəl", "До поездки"),
    "After": ("Səfərdən sonra", "После поездки"),
    "6 photos + signature": ("6 foto + imza", "6 фото + подпись"),
    "Amount": ("Məbləğ", "Сумма"),
    "Days open": ("Açıq qalan günlər", "Дней открыто"),
    "Last trip": ("Son səfər", "Последняя поездка"),
    "User": ("İstifadəçi", "Пользователь"),
    "Details": ("Təfərrüatlar", "Подробности"),
    "Review": ("Rəy", "Отзыв"),
    "Author": ("Müəllif", "Автор"),
    "Text": ("Mətn", "Текст"),
    "Payment": ("Ödəniş", "Платёж"),
    "Payer": ("Ödəyən", "Плательщик"),
    "Method": ("Üsul", "Способ"),
    "Gateway": ("Ödəniş şlüzü", "Платёжный шлюз"),
    "Reference": ("İstinad", "Референс"),
    "Message": ("Mesaj", "Сообщение"),
    "Audience": ("Auditoriya", "Аудитория"),
    "Opened": ("Açılıb", "Открыли"),
    "All users": ("Bütün istifadəçilər", "Все пользователи"),
    "EV riders": ("EV istifadəçiləri", "Клиенты EV"),
    "Hosts": ("Sahibkarlar", "Владельцы"),
    "Golf guests": ("Qolf qonaqları", "Гости гольфа"),
    "Push": ("Push", "Пуш"),
    "Push + News card": ("Push + xəbər kartı", "Пуш + карточка новости"),
    "Code": ("Kod", "Код"),
    "Limit": ("Limit", "Лимит"),
    "Valid until": ("Etibarlıdır", "Действует до"),
    "Plan": ("Plan", "План"),
    "Discount": ("Endirim", "Скидка"),
    "Renews": ("Yenilənmə", "Продление"),
    "Automatically": ("Avtomatik", "Автоматически"),
    "Tariff": ("Tarif", "Тариф"),
    "Applies to": ("Tətbiq olunur", "Применяется к"),
    "Zone": ("Zona", "Зона"),
    "Parking": ("Parkinq", "Парковка"),
    "Cars inside": ("İçəridəki avtomobillər", "Машин внутри"),
    "Role": ("Rol", "Роль"),
    "Sea Breeze team": ("Sea Breeze komandası", "Команда Sea Breeze"),
    "Golf driver": ("Qolf sürücüsü", "Водитель гольф-кара"),
    "EV driver": ("EV sürücüsü", "Водитель EV"),
    "Transfer host": ("Transfer sahibkarı", "Владелец (трансфер)"),
    "Route": ("Marşrut", "Маршрут"),
    "Driver": ("Sürücü", "Водитель"),
    "Departure": ("Yola düşmə", "Отправление"),
    "Cancellation": ("Ləğv qaydası", "Условия отмены"),
    "Flexible": ("Çevik", "Гибкие"),
    "Strict": ("Sərt", "Строгие"),
    "Team": ("Komanda", "Команда"),
    "Invoice e-mail": ("Hesab-faktura e-poçtu", "Почта для счетов"),
    "Monthly limit": ("Aylıq limit", "Месячный лимит"),
    "Group": ("Qrup", "Группа"),
    "Can write": ("Dəyişə bilər", "Может изменять"),
    "Yes": ("Bəli", "Да"),
    "Own module only": ("Yalnız öz modulu", "Только свой модуль"),
    "File": ("Fayl", "Файл"),
    "Updated": ("Yeniləndi", "Обновлён"),
    "Make": ("Marka", "Марка"),
    "Models": ("Modellər", "Модели"),
    "Value": ("Dəyər", "Значение"),
    "On": ("Açıq", "Вкл."),
    "Off": ("Bağlı", "Выкл."),
    # CSV headers
    "ID": ("ID", "ID"),
    "Title": ("Ad", "Название"),
    "Created": ("Yaradılıb", "Создано"),
}

EXTRA_SOURCE_ONLY = []  # keys that are proper names stay English


def main() -> None:
    catalogue = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for key in sorted(T):
        az, ru = T[key]
        catalogue["strings"][key] = {
            "extractionState": "manual",
            "localizations": {
                "az": {"stringUnit": {"state": "translated", "value": az}},
                "ru": {"stringUnit": {"state": "translated", "value": ru}},
            },
        }
    out = pathlib.Path(__file__).resolve().parent.parent / "Packages/AdminKit/Sources/AdminFeatures/Resources/Localizable.xcstrings"
    out.write_text(json.dumps(catalogue, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"{len(T)} strings → {out}")


if __name__ == "__main__":
    main()
